# Generated by Django 2.2.5 on 2021-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dsretime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('protype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('one_md5', models.CharField(max_length=1000)),
                ('two_md5', models.CharField(max_length=1000)),
                ('page_error', models.CharField(max_length=100)),
                ('code_error', models.CharField(max_length=100)),
                ('ky_count', models.CharField(max_length=100)),
                ('wz_count', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sacntask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=100)),
                ('gjlx', models.CharField(max_length=100)),
                ('gjfz', models.CharField(max_length=100)),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('md5', models.CharField(max_length=1000)),
                ('md5_jc', models.CharField(max_length=1000)),
                ('lt_status', models.CharField(max_length=100)),
                ('wz_status', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=100)),
                ('xsd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tokenStr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
