# Generated by Django 2.2.5 on 2021-07-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='time',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
